# Generated by Django 5.2.11 on 2026-02-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('backend', 'Backend Developer'), ('frontend', 'Frontend Developer'), ('product_manager', 'Product Manager'), ('uiux_designer', 'UIUX Designer')], default='backend', max_length=20),
        ),
    ]
