# Generated by Django 5.2.11 on 2026-02-22 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_dailysummary_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='target_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
